[any-nix-shell]
src.git = "https://github.com/haslersn/any-nix-shell"
fetch.github = "haslersn/any-nix-shell"

[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"
cargo_lock = "Cargo.lock"

[spacemacs-theme]
src.git = "https://github.com/Th3Whit3Wolf/Space-Theme"
fetch.github = "Th3Whit3Wolf/Space-Theme"

[sanFrancisco-font]
src.git = "https://github.com/supermarin/YosemiteSanFranciscoFont"
fetch.github = "supermarin/YosemiteSanFranciscoFont"

[sanFranciscoMono-font]
src.git = "https://github.com/supercomputra/SF-Mono-Font"
fetch.github = "supercomputra/SF-Mono-Font"

[SFMono-nerdfont]
src.git = "https://github.com/epk/SF-Mono-Nerd-Font"
fetch.github = "epk/SF-Mono-Nerd-Font"

[eww]
src.git = "https://github.com/elkowar/eww"
fetch.github = "elkowar/eww"
extract = ["flake.lock"]

# Vim Plugins
[vimP-parinfer-rust]
src.git = "https://github.com/eraserhd/parinfer-rust"
fetch.github = "eraserhd/parinfer-rust"
cargo_lock = "Cargo.lock"

[vimPlugins-ron-vim]
src.git = "https://github.com/ron-rs/ron.vim"
fetch.github = "ron-rs/ron.vim"

[vimPlugins-vim-cargo-make]
src.git = "https://github.com/nastevens/vim-cargo-make"
fetch.github = "nastevens/vim-cargo-make"

[vimPlugins-vim-duckscript]
src.git = "https://github.com/nastevens/vim-duckscript"
fetch.github = "nastevens/vim-duckscript"

# VSCode Extensions
[vscode-extensions-roscop.activefileinstatusbar]
src.vsmarketplace = "roscop.activefileinstatusbar"
fetch.vsmarketplace = "roscop.activefileinstatusbar"

[vscode-extensions-cometeer.spacemacs]
src.vsmarketplace = "cometeer.spacemacs"
fetch.vsmarketplace = "cometeer.spacemacs"

[vscode-extensions-spikespaz.vscode-smoothtype]
src.vsmarketplace = "spikespaz.vscode-smoothtype"
fetch.vsmarketplace = "spikespaz.vscode-smoothtype"

[vscode-extensions-ms-vscode-remote.remote-ssh]
src.vsmarketplace = "ms-vscode-remote.remote-ssh"
fetch.vsmarketplace = "ms-vscode-remote.remote-ssh"

[vscode-extensions-ms-vscode-remote.remote-ssh-edit]
src.vsmarketplace = "ms-vscode-remote.remote-ssh-edit"
fetch.vsmarketplace = "ms-vscode-remote.remote-ssh-edit"

[vscode-extensions-aaron-bond.better-comments]
src.vsmarketplace = "aaron-bond.better-comments"
fetch.vsmarketplace = "aaron-bond.better-comments"

[vscode-extensions-wwm.better-align]
src.vsmarketplace = "wwm.better-align"
fetch.vsmarketplace = "wwm.better-align"

[vscode-extensions-christian-kohler.path-intellisense]
src.vsmarketplace = "christian-kohler.path-intellisense"
fetch.vsmarketplace = "christian-kohler.path-intellisense"

[vscode-extensions-hardikmodha.create-tests]
src.vsmarketplace = "hardikmodha.create-tests"
fetch.vsmarketplace = "hardikmodha.create-tests"

[vscode-extensions-softwaredotcom.swdc-vscode]
src.vsmarketplace = "softwaredotcom.swdc-vscode"
fetch.vsmarketplace = "softwaredotcom.swdc-vscode"

[vscode-extensions-ryu1kn.edit-with-shell]
src.vsmarketplace = "ryu1kn.edit-with-shell"
fetch.vsmarketplace = "ryu1kn.edit-with-shell"

[vscode-extensions-oderwat.indent-rainbow]
src.vsmarketplace = "oderwat.indent-rainbow"
fetch.vsmarketplace = "oderwat.indent-rainbow"

[vscode-extensions-KnisterPeter.vscode-github]
src.vsmarketplace = "KnisterPeter.vscode-github"
fetch.vsmarketplace = "KnisterPeter.vscode-github"

[vscode-extensions-mikestead.dotenv]
src.vsmarketplace = "mikestead.dotenv"
fetch.vsmarketplace = "mikestead.dotenv"

[vscode-extensions-kruemelkatze.vscode-dashboard]
src.vsmarketplace = "kruemelkatze.vscode-dashboard"
fetch.vsmarketplace = "kruemelkatze.vscode-dashboard"

[vscode-extensions-alefragnani.project-manager]
src.vsmarketplace = "alefragnani.project-manager"
fetch.vsmarketplace = "alefragnani.project-manager"

[vscode-extensions-shd101wyy.markdown-preview-enhanced]
src.vsmarketplace = "shd101wyy.markdown-preview-enhanced"
fetch.vsmarketplace = "shd101wyy.markdown-preview-enhanced"

[vscode-extensions-dendron.dendron]
src.vsmarketplace = "dendron.dendron"
fetch.vsmarketplace = "dendron.dendron"

[vscode-extensions-eamodio.gitlens]
src.vsmarketplace = "eamodio.gitlens"
fetch.vsmarketplace = "eamodio.gitlens"

[vscode-extensions-rubbersheep.gi]
src.vsmarketplace = "rubbersheep.gi"
fetch.vsmarketplace = "rubbersheep.gi"

[vscode-extensions-vsls-contrib.gistfs]
src.vsmarketplace = "vsls-contrib.gistfs"
fetch.vsmarketplace = "vsls-contrib.gistfs"

[vscode-extensions-formulahendry.code-runner]
src.vsmarketplace = "formulahendry.code-runner"
fetch.vsmarketplace = "formulahendry.code-runner"

[vscode-extensions-donjayamanne.githistory]
src.vsmarketplace = "donjayamanne.githistory"
fetch.vsmarketplace = "donjayamanne.githistory"

[vscode-extensions-felipecaputo.git-project-manager]
src.vsmarketplace = "felipecaputo.git-project-manager"
fetch.vsmarketplace = "felipecaputo.git-project-manager"

[vscode-extensions-qezhu.gitlink]
src.vsmarketplace = "qezhu.gitlink"
fetch.vsmarketplace = "qezhu.gitlink"

[vscode-extensions-lamartire.git-indicators]
src.vsmarketplace = "lamartire.git-indicators"
fetch.vsmarketplace = "lamartire.git-indicators"

[vscode-extensions-erichbehrens.pull-request-monitor]
src.vsmarketplace = "erichbehrens.pull-request-monitor"
fetch.vsmarketplace = "erichbehrens.pull-request-monitor"

[vscode-extensions-nash.awesome-flutter-snippets]
src.vsmarketplace = "nash.awesome-flutter-snippets"
fetch.vsmarketplace = "nash.awesome-flutter-snippets"

[vscode-extensions-dzhavat.css-initial-value]
src.vsmarketplace = "dzhavat.css-initial-value"
fetch.vsmarketplace = "dzhavat.css-initial-value"

[vscode-extensions-dart-code.dart-code]
src.vsmarketplace = "dart-code.dart-code"
fetch.vsmarketplace = "dart-code.dart-code"

[vscode-extensions-dart-code.flutter]
src.vsmarketplace = "dart-code.flutter"
fetch.vsmarketplace = "dart-code.flutter"

[vscode-extensions-mathiasfrohlich.kotlin]
src.vsmarketplace = "mathiasfrohlich.kotlin"
fetch.vsmarketplace = "mathiasfrohlich.kotlin"

[vscode-extensions-alefragnani.pascal]
src.vsmarketplace = "alefragnani.pascal"
fetch.vsmarketplace = "alefragnani.pascal"

[vscode-extensions-alefragnani.pascal-formatter]
src.vsmarketplace = "alefragnani.pascal-formatter"
fetch.vsmarketplace = "alefragnani.pascal-formatter"

[vscode-extensions-esbenp.prettier-vscode]
src.vsmarketplace = "esbenp.prettier-vscode"
fetch.vsmarketplace = "esbenp.prettier-vscode"

[vscode-extensions-jeroen-meijer.pubspec-assist]
src.vsmarketplace = "jeroen-meijer.pubspec-assist"
fetch.vsmarketplace = "jeroen-meijer.pubspec-assist"

[vscode-extensions-ms-python.python]
src.vsmarketplace = "ms-python.python"
fetch.vsmarketplace = "ms-python.python"

[vscode-extensions-humao.rest-client]
src.vsmarketplace = "humao.rest-client"
fetch.vsmarketplace = "humao.rest-client"

[vscode-extensions-adpyke.codesnap]
src.vsmarketplace = "adpyke.codesnap"
fetch.vsmarketplace = "adpyke.codesnap"

[vscode-extensions-msjsdiag.vscode-react-native]
src.vsmarketplace = "msjsdiag.vscode-react-native"
fetch.vsmarketplace = "msjsdiag.vscode-react-native"

[vscode-extensions-dbaeumer.vscode-eslint]
src.vsmarketplace = "dbaeumer.vscode-eslint"
fetch.vsmarketplace = "dbaeumer.vscode-eslint"

[vscode-extensions-pflannery.vscode-versionlens]
src.vsmarketplace = "pflannery.vscode-versionlens"
fetch.vsmarketplace = "pflannery.vscode-versionlens"

[vscode-extensions-svelte.svelte-vscode]
src.vsmarketplace = "svelte.svelte-vscode"
fetch.vsmarketplace = "svelte.svelte-vscode"

[vscode-extensions-rust-lang.rust]
src.vsmarketplace = "rust-lang.rust"
fetch.vsmarketplace = "rust-lang.rust"

[vscode-extensions-b4dm4n.nixpkgs-fmt]
src.vsmarketplace = "b4dm4n.nixpkgs-fmt"
fetch.vsmarketplace = "b4dm4n.nixpkgs-fmt"

[vscode-extensions-jnoortheen.nix-ide]
src.vsmarketplace = "jnoortheen.nix-ide"
fetch.vsmarketplace = "jnoortheen.nix-ide"

[vscode-extensions-arrterian.nix-env-selector]
src.vsmarketplace = "arrterian.nix-env-selector"
fetch.vsmarketplace = "arrterian.nix-env-selector"

[vscode-extensions-rebornix.Ruby]
src.vsmarketplace = "rebornix.Ruby"
fetch.vsmarketplace = "rebornix.Ruby"

[vscode-extensions-misogi.ruby-rubocop]
src.vsmarketplace = "misogi.ruby-rubocop"
fetch.vsmarketplace = "misogi.ruby-rubocop"

[vscode-extensions-castwide.solargraph]
src.vsmarketplace = "castwide.solargraph"
fetch.vsmarketplace = "castwide.solargraph"

[vscode-extensions-hridoy.rails-snippets]
src.vsmarketplace = "hridoy.rails-snippets"
fetch.vsmarketplace = "hridoy.rails-snippets"

[vscode-extensions-vortizhe.simple-ruby-erb]
src.vsmarketplace = "vortizhe.simple-ruby-erb"
fetch.vsmarketplace = "vortizhe.simple-ruby-erb"

[vscode-extensions-belfz.search-crates-io]
src.vsmarketplace = "belfz.search-crates-io"
fetch.vsmarketplace = "belfz.search-crates-io"

[vscode-extensions-batisteo.vscode-django]
src.vsmarketplace = "batisteo.vscode-django"
fetch.vsmarketplace = "batisteo.vscode-django"

[vscode-extensions-CodeYard.flask-snippets]
src.vsmarketplace = "CodeYard.flask-snippets"
fetch.vsmarketplace = "CodeYard.flask-snippets"

[vscode-extensions-frhtylcn.pythonsnippets]
src.vsmarketplace = "frhtylcn.pythonsnippets"
fetch.vsmarketplace = "frhtylcn.pythonsnippets"

[vscode-extensions-extensionFromVscodeMarketplace]
src.vsmarketplace = "extensionFromVscodeMarketplace"
fetch.vsmarketplace = "extensionFromVscodeMarketplace"

[vscode-extensions-njpwerner.autodocstring]
src.vsmarketplace = "njpwerner.autodocstring"
fetch.vsmarketplace = "njpwerner.autodocstring"

[vscode-extensions-dongli.python-preview]
src.vsmarketplace = "dongli.python-preview"
fetch.vsmarketplace = "dongli.python-preview"

[vscode-extensions-ms-toolsai.jupyter]
src.vsmarketplace = "ms-toolsai.jupyter"
fetch.vsmarketplace = "ms-toolsai.jupyter"

[vscode-extensions-formulahendry.auto-close-tag]
src.vsmarketplace = "formulahendry.auto-close-tag"
fetch.vsmarketplace = "formulahendry.auto-close-tag"

[vscode-extensions-formulahendry.auto-rename-tag]
src.vsmarketplace = "formulahendry.auto-rename-tag"
fetch.vsmarketplace = "formulahendry.auto-rename-tag"

[vscode-extensions-auchenberg.vscode-browser-preview]
src.vsmarketplace = "auchenberg.vscode-browser-preview"
fetch.vsmarketplace = "auchenberg.vscode-browser-preview"

[vscode-extensions-ritwickdey.LiveServer]
src.vsmarketplace = "ritwickdey.LiveServer"
fetch.vsmarketplace = "ritwickdey.LiveServer"

[vscode-extensions-xabikos.JavaScriptSnippets]
src.vsmarketplace = "xabikos.JavaScriptSnippets"
fetch.vsmarketplace = "xabikos.JavaScriptSnippets"

[vscode-extensions-WallabyJs.quokka-vscode]
src.vsmarketplace = "WallabyJs.quokka-vscode"
fetch.vsmarketplace = "WallabyJs.quokka-vscode"

[vscode-extensions-ritwickdey.live-sass]
src.vsmarketplace = "ritwickdey.live-sass"
fetch.vsmarketplace = "ritwickdey.live-sass"

[vscode-extensions-dsznajder.es7-react-js-snippets]
src.vsmarketplace = "dsznajder.es7-react-js-snippets"
fetch.vsmarketplace = "dsznajder.es7-react-js-snippets"

[vscode-extensions-denoland.vscode-deno]
src.vsmarketplace = "denoland.vscode-deno"
fetch.vsmarketplace = "denoland.vscode-deno"

[vscode-extensions-betterthantomorrow.calva]
src.vsmarketplace = "betterthantomorrow.calva"
fetch.vsmarketplace = "betterthantomorrow.calva"

[vscode-extensions-ailisp.commonlisp-vscode]
src.vsmarketplace = "ailisp.commonlisp-vscode"
fetch.vsmarketplace = "ailisp.commonlisp-vscode"

[vscode-extensions-ailisp.strict-paredit]
src.vsmarketplace = "ailisp.strict-paredit"
fetch.vsmarketplace = "ailisp.strict-paredit"

[vscode-extensions-scalameta.metals]
src.vsmarketplace = "scalameta.metals"
fetch.vsmarketplace = "scalameta.metals"

[vscode-extensions-rogalmic.bash-debug]
src.vsmarketplace = "rogalmic.bash-debug"
fetch.vsmarketplace = "rogalmic.bash-debug"

[vscode-extensions-Remisa.shellman]
src.vsmarketplace = "Remisa.shellman"
fetch.vsmarketplace = "Remisa.shellman"

[vscode-extensions-ccls-project.ccls]
src.vsmarketplace = "ccls-project.ccls"
fetch.vsmarketplace = "ccls-project.ccls"

[vscode-extensions-stylelint.vscode-stylelint]
src.vsmarketplace = "stylelint.vscode-stylelint"
fetch.vsmarketplace = "stylelint.vscode-stylelint"

[vscode-extensions-sumneko.lua]
src.vsmarketplace = "sumneko.lua"
fetch.vsmarketplace = "sumneko.lua"

[vscode-extensions-christian-kohler.npm-intellisense]
src.vsmarketplace = "christian-kohler.npm-intellisense"
fetch.vsmarketplace = "christian-kohler.npm-intellisense"

[vscode-extensions-DominicVonk.parameter-hints]
src.vsmarketplace = "DominicVonk.parameter-hints"
fetch.vsmarketplace = "DominicVonk.parameter-hints"

[vscode-extensions-HookyQR.beautify]
src.vsmarketplace = "HookyQR.beautify"
fetch.vsmarketplace = "HookyQR.beautify"

[vscode-extensions-yatki.vscode-surround]
src.vsmarketplace = "yatki.vscode-surround"
fetch.vsmarketplace = "yatki.vscode-surround"

[vscode-extensions-steoates.autoimport]
src.vsmarketplace = "steoates.autoimport"
fetch.vsmarketplace = "steoates.autoimport"

[vscode-extensions-foxundermoon.shell-format]
src.vsmarketplace = "foxundermoon.shell-format"
fetch.vsmarketplace = "foxundermoon.shell-format"

[vscode-extensions-vincaslt.highlight-matching-tag]
src.vsmarketplace = "vincaslt.highlight-matching-tag"
fetch.vsmarketplace = "vincaslt.highlight-matching-tag"

[vscode-extensions-cssho.vscode-svgviewer]
src.vsmarketplace = "cssho.vscode-svgviewer"
fetch.vsmarketplace = "cssho.vscode-svgviewer"

[vscode-extensions-stkb.rewrap]
src.vsmarketplace = "stkb.rewrap"
fetch.vsmarketplace = "stkb.rewrap"

[vscode-extensions-zxh404.vscode-proto3]
src.vsmarketplace = "zxh404.vscode-proto3"
fetch.vsmarketplace = "zxh404.vscode-proto3"

[vscode-extensions-skellock.just]
src.vsmarketplace = "skellock.just"
fetch.vsmarketplace = "skellock.just"

[vscode-extensions-dunstontc.viml]
src.vsmarketplace = "dunstontc.viml"
fetch.vsmarketplace = "dunstontc.viml"

[vscode-extensions-julialang.language-julia]
src.vsmarketplace = "julialang.language-julia"
fetch.vsmarketplace = "julialang.language-julia"

[vscode-extensions-Zignd.html-css-class-completion]
src.vsmarketplace = "Zignd.html-css-class-completion"
fetch.vsmarketplace = "Zignd.html-css-class-completion"

[vscode-extensions-mrmlnc.vscode-autoprefixer]
src.vsmarketplace = "mrmlnc.vscode-autoprefixer"
fetch.vsmarketplace = "mrmlnc.vscode-autoprefixer"

[vscode-extensions-pranaygp.vscode-css-peek]
src.vsmarketplace = "pranaygp.vscode-css-peek"
fetch.vsmarketplace = "pranaygp.vscode-css-peek"

[vscode-extensions-thekalinga.bootstrap4-vscode]
src.vsmarketplace = "thekalinga.bootstrap4-vscode"
fetch.vsmarketplace = "thekalinga.bootstrap4-vscode"

[vscode-extensions-octref.vetur]
src.vsmarketplace = "octref.vetur"
fetch.vsmarketplace = "octref.vetur"

[vscode-extensions-johnpapa.Angular2]
src.vsmarketplace = "johnpapa.Angular2"
fetch.vsmarketplace = "johnpapa.Angular2"

[vscode-extensions-amatiasq.sort-imports]
src.vsmarketplace = "amatiasq.sort-imports"
fetch.vsmarketplace = "amatiasq.sort-imports"

[vscode-extensions-wix.vscode-import-cost]
src.vsmarketplace = "wix.vscode-import-cost"
fetch.vsmarketplace = "wix.vscode-import-cost"

[vscode-extensions-anteprimorac.html-end-tag-labels]
src.vsmarketplace = "anteprimorac.html-end-tag-labels"
fetch.vsmarketplace = "anteprimorac.html-end-tag-labels"

[vscode-extensions-streetsidesoftware.code-spell-checker]
src.vsmarketplace = "streetsidesoftware.code-spell-checker"
fetch.vsmarketplace = "streetsidesoftware.code-spell-checker"

[vscode-extensions-devonray.snippet]
src.vsmarketplace = "devonray.snippet"
fetch.vsmarketplace = "devonray.snippet"
