[any-nix-shell]
src.git = "https://github.com/haslersn/any-nix-shell"
fetch.github = "haslersn/any-nix-shell"

[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"
cargo_lock = "Cargo.lock"

[spacemacs-theme]
src.git = "https://github.com/Th3Whit3Wolf/Space-Theme"
fetch.github = "Th3Whit3Wolf/Space-Theme"

[sanFrancisco-font]
src.git = "https://github.com/supermarin/YosemiteSanFranciscoFont"
fetch.github = "supermarin/YosemiteSanFranciscoFont"

[sanFranciscoMono-font]
src.git = "https://github.com/supercomputra/SF-Mono-Font"
fetch.github = "supercomputra/SF-Mono-Font"

[SFMono-nerdfont]
src.git = "https://github.com/epk/SF-Mono-Nerd-Font"
fetch.github = "epk/SF-Mono-Nerd-Font"

[eww]
src.git = "https://github.com/elkowar/eww"
fetch.github = "elkowar/eww"
extract = ["flake.lock"]

# Vim Plugins
[vimP-parinfer-rust]
src.git = "https://github.com/eraserhd/parinfer-rust"
fetch.github = "eraserhd/parinfer-rust"
cargo_lock = "Cargo.lock"

[vimPlugins-ron-vim]
src.git = "https://github.com/ron-rs/ron.vim"
fetch.github = "ron-rs/ron.vim"

[vimPlugins-vim-cargo-make]
src.git = "https://github.com/nastevens/vim-cargo-make"
fetch.github = "nastevens/vim-cargo-make"

[vimPlugins-vim-duckscript]
src.git = "https://github.com/nastevens/vim-duckscript"
fetch.github = "nastevens/vim-duckscript"
